### ISSUE TITLE
v1.2.0 pre-release checklist

### ISSUE THREAD

**Issue by jaeddy** [CRI-iAtlas/shiny-iatlas#167]
- [x] Address, close, or re-label any open issues for the [`v1.2.0` milestone](https://github.com/CRI-iAtlas/shiny-iatlas/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.2.0)
- [x] Check out `develop` branch, `git pull` to ensure latest version of repo code/data
- [ ] Test and verify that installation instructions work
- [ ] Run any existing unit tests and verify that all pass
- [ ] Test and verify that app functionality works as expected
- [ ] Clean up old/unused files (e.g., `_DESCRIPTION` and the `iatlas/` folder)
- [x] Commit any new changes to `develop` branch
- [ ] Create a new pull request for `develop` into `master`
- [ ] Review and merge PR
- [ ] Check out `master` branch, `git pull` to retrieve all changes
- [ ] **Recommended:** install the [**release-it**](https://github.com/release-it/release-it) package
  - (Optional) Create and activate a new `conda` environment with `nodejs` (which includes `npm`)
  - Run the following command: `npm install -g release-it`
- [ ] Test the release process with `--dry-run` flag: `release-it minor --dry-run` (respond `Y` to all prompts) 

When you've finished all the steps above, you're ready to go! **Note:** we can update release notes anytime.
